using Jaunty.Tests.Entities;
using Jaunty.Tests.Helpers.Dialects;

namespace Jaunty.Tests.Integration.Write;

public class DatabaseGeneratedTests : IClassFixture<DialectFixture>
{
    private readonly DialectFixture _fixture;

    public DatabaseGeneratedTests(DialectFixture fixture)
    {
        _fixture = fixture;
    }

    [Theory]
    [SqlServer]
    [Postgres]
    [MariaDB]
    [MicrosoftSqlite]
    [SystemSqlite]
    public void Insert_IdentityColumn_ReturnsGeneratedId(DialectInfo dialect)
    {
        using var ctx = _fixture.GetWriteContext(dialect);
        var entity = new BulkTestEntity { Name = "Test1", Value = 100 };

        long id = ctx.Connection.Insert(entity);

        Assert.True(id > 0);
    }

    [Theory]
    [SqlServer]
    [Postgres]
    [MariaDB]
    [MicrosoftSqlite]
    [SystemSqlite]
    public void Insert_IdentityColumn_AutoIncrements(DialectInfo dialect)
    {
        using var ctx = _fixture.GetWriteContext(dialect);
        var entity1 = new BulkTestEntity { Name = "Test1", Value = 100 };
        var entity2 = new BulkTestEntity { Name = "Test2", Value = 200 };

        long id1 = ctx.Connection.Insert(entity1);
        long id2 = ctx.Connection.Insert(entity2);

        Assert.True(id2 > id1);
    }

    [Theory]
    [SqlServer]
    [Postgres]
    [MariaDB]
    [MicrosoftSqlite]
    [SystemSqlite]
    public void Insert_IdentityColumn_IgnoresProvidedId(DialectInfo dialect)
    {
        using var ctx = _fixture.GetWriteContext(dialect);
        var entity = new BulkTestEntity { Id = 999, Name = "Test1", Value = 100 };

        long id = ctx.Connection.Insert(entity);

        Assert.NotEqual(999, id);
        Assert.True(id > 0);
    }

    [Theory]
    [SqlServer]
    [Postgres]
    [MariaDB]
    [MicrosoftSqlite]
    [SystemSqlite]
    public void BulkInsert_IdentityColumns_AllAutoGenerated(DialectInfo dialect)
    {
        using var ctx = _fixture.GetWriteContext(dialect);
        var entities = new List<BulkTestEntity>
        {
            new() { Name = "Test1", Value = 100 },
            new() { Name = "Test2", Value = 200 },
            new() { Name = "Test3", Value = 300 }
        };

        int inserted = ctx.Connection.BulkInsert(entities);

        Assert.Equal(3, inserted);

        var results = ctx.Connection.Query<BulkTestEntity>("SELECT id AS Id, name AS Name, value AS Value FROM bulk_test ORDER BY id");
        Assert.Equal(3, results.Count);
        Assert.All(results, r => Assert.True(r.Id > 0));
        Assert.True(results[1].Id > results[0].Id);
        Assert.True(results[2].Id > results[1].Id);
    }

    [Theory]
    [SqlServer]
    [Postgres]
    [MariaDB]
    [MicrosoftSqlite]
    [SystemSqlite]
    public void Update_DoesNotModifyIdentityColumn(DialectInfo dialect)
    {
        using var ctx = _fixture.GetWriteContext(dialect);
        var entity = new BulkTestEntity { Name = "Original", Value = 100 };
        entity.Id = ctx.Connection.Insert(entity);

        long originalId = entity.Id;
        entity.Name = "Updated";
        entity.Value = 200;

        int rows = ctx.Connection.Update(entity);

        Assert.Equal(1, rows);

        var result = ctx.Connection.QueryFirst<BulkTestEntity>(
            "SELECT id AS Id, name AS Name, value AS Value FROM bulk_test WHERE id = @Id",
            new { Id = originalId });
        Assert.Equal(originalId, result.Id);
        Assert.Equal("Updated", result.Name);
        Assert.Equal(200, result.Value);
    }
}