using System.Data;
using System.Data.SQLite;

using Jaunty;
using Jaunty.Attributes;
using Jaunty.Tests.Entities;

namespace Jaunty.Tests.Integration.Write;

public class DatabaseGeneratedTests : IDisposable
{
    private readonly SQLiteConnection _connection;
    private bool _disposed;

    public DatabaseGeneratedTests()
    {
        _connection = new SQLiteConnection("Data Source=:memory:");
        _connection.Open();
        CreateTestTables();
    }

    public void Dispose()
    {
        if (_disposed) return;
        _connection?.Dispose();
        _disposed = true;
        GC.SuppressFinalize(this);
    }

    private void CreateTestTables()
    {
        using var cmd = _connection.CreateCommand();
        cmd.CommandText = @"
            CREATE TABLE bulk_test (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                name TEXT NOT NULL,
                value INTEGER NOT NULL
            )";
        cmd.ExecuteNonQuery();
    }

    [Fact]
    public void Insert_IdentityColumn_ReturnsGeneratedId()
    {
        var entity = new BulkTestEntity { Name = "Test1", Value = 100 };

        long id = _connection.Insert(entity);

        Assert.True(id > 0);
    }

    [Fact]
    public void Insert_IdentityColumn_AutoIncrements()
    {
        var entity1 = new BulkTestEntity { Name = "Test1", Value = 100 };
        var entity2 = new BulkTestEntity { Name = "Test2", Value = 200 };

        long id1 = _connection.Insert(entity1);
        long id2 = _connection.Insert(entity2);

        Assert.True(id2 > id1);
    }

    [Fact]
    public void Insert_IdentityColumn_IgnoresProvidedId()
    {
        var entity = new BulkTestEntity { Id = 999, Name = "Test1", Value = 100 };

        long id = _connection.Insert(entity);

        Assert.NotEqual(999, id);
        Assert.True(id > 0);
    }

    [Fact]
    public void BulkInsert_IdentityColumns_AllAutoGenerated()
    {
        var entities = new List<BulkTestEntity>
        {
            new() { Name = "Test1", Value = 100 },
            new() { Name = "Test2", Value = 200 },
            new() { Name = "Test3", Value = 300 }
        };

        int inserted = _connection.BulkInsert(entities);

        Assert.Equal(3, inserted);

        var results = _connection.Query<BulkTestEntity>("SELECT id AS Id, name AS Name, value AS Value FROM bulk_test ORDER BY id");
        Assert.Equal(3, results.Count);
        Assert.All(results, r => Assert.True(r.Id > 0));
        Assert.True(results[1].Id > results[0].Id);
        Assert.True(results[2].Id > results[1].Id);
    }

    [Fact]
    public void Update_DoesNotModifyIdentityColumn()
    {
        var entity = new BulkTestEntity { Name = "Original", Value = 100 };
        entity.Id = _connection.Insert(entity);

        long originalId = entity.Id;
        entity.Name = "Updated";
        entity.Value = 200;

        int rows = Jaunty.Update(_connection, entity);

        Assert.Equal(1, rows);

        var result = _connection.QueryFirst<BulkTestEntity>(
            "SELECT id AS Id, name AS Name, value AS Value FROM bulk_test WHERE id = @Id",
            new { Id = originalId });
        Assert.Equal(originalId, result.Id);
        Assert.Equal("Updated", result.Name);
        Assert.Equal(200, result.Value);
    }
}

