<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>netstandard2.0;net8.0</TargetFrameworks>
		<!--<TargetFramework>net8.0</TargetFramework>-->
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<PropertyGroup Condition="'$(TargetFramework)' == 'netstandard2.0'">
		<LangVersion>latest</LangVersion>
		<!--<DefineConstants>NETSTANDARD2_0</DefineConstants>-->
	</PropertyGroup>
	
	<PropertyGroup Condition="'$(TargetFramework)' == 'net8.0'">
		<LangVersion>latest</LangVersion>
		<Nullable>enable</Nullable>
		<!--<DefineConstants>NET8_0</DefineConstants>-->
	</PropertyGroup>

	<ItemGroup>
		<AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
			<_Parameter1>Jaunty.Tests</_Parameter1>
		</AssemblyAttribute>
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Internal\Mapping\" />
	</ItemGroup>

	<PropertyGroup>
		<PackageId>Beparey.Jaunty</PackageId>
		<Version>2026.01.01</Version>
		<Authors>Syed Beparey</Authors>
		<Description>A fast ORM</Description>
		<RepositoryUrl>https://github.com/beparey/jaunty</RepositoryUrl>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<Nullable>enable</Nullable>
		<ErrorReport>none</ErrorReport>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|netstandard2.0|AnyCPU'">
	  <WarningLevel>5</WarningLevel>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|netstandard2.0|AnyCPU'">
	  <WarningLevel>5</WarningLevel>
	</PropertyGroup>
</Project>
