-- Reference DDL for the eShopOnWeb Jaunty torture-test (PostgreSQL 16).
-- Reference copy only: runtime schema creation is done by the embedded C# DDL in
-- src/Infrastructure/Data/Persistence/PostgresSchema.cs. Column shapes mirror Rows.cs.

DROP TABLE IF EXISTS OrderItems;
DROP TABLE IF EXISTS Orders;
DROP TABLE IF EXISTS BasketItems;
DROP TABLE IF EXISTS Baskets;
DROP TABLE IF EXISTS Catalog;
DROP TABLE IF EXISTS CatalogTypes;
DROP TABLE IF EXISTS CatalogBrands;

CREATE TABLE IF NOT EXISTS CatalogBrands (
    Id      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Brand   VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS CatalogTypes (
    Id      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Type    VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS Catalog (
    Id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Name            VARCHAR(255) NOT NULL,
    Description     TEXT NOT NULL,
    Price           DECIMAL(18,2) NOT NULL,
    PictureUri      VARCHAR(1000) NULL,
    CatalogTypeId   INT NOT NULL,
    CatalogBrandId  INT NOT NULL
);

CREATE TABLE IF NOT EXISTS Baskets (
    Id      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    BuyerId VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS BasketItems (
    Id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    UnitPrice       DECIMAL(18,2) NOT NULL,
    Quantity        INT NOT NULL,
    CatalogItemId   INT NOT NULL,
    BasketId        INT NOT NULL
);

CREATE TABLE IF NOT EXISTS Orders (
    Id                      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    BuyerId                 VARCHAR(255) NOT NULL,
    OrderDate               VARCHAR(64) NOT NULL,
    ShipToAddress_Street    VARCHAR(255) NOT NULL,
    ShipToAddress_City      VARCHAR(255) NOT NULL,
    ShipToAddress_State     VARCHAR(255) NULL,
    ShipToAddress_Country   VARCHAR(255) NOT NULL,
    ShipToAddress_ZipCode   VARCHAR(64) NOT NULL
);

CREATE TABLE IF NOT EXISTS OrderItems (
    Id                          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    OrderId                     INT NOT NULL,
    UnitPrice                   DECIMAL(18,2) NOT NULL,
    Units                       INT NOT NULL,
    ItemOrdered_CatalogItemId   INT NOT NULL,
    ItemOrdered_ProductName     VARCHAR(255) NOT NULL,
    ItemOrdered_PictureUri      VARCHAR(1000) NOT NULL
);
