using Microsoft.Data.Sqlite;

using Jaunty.Scaffolding.Abstractions;
using Jaunty.Scaffolding.CodeGeneration;
using Jaunty.Scaffolding.Configuration;
using Jaunty.Scaffolding.Schema;

namespace Jaunty.Scaffolding.Tests.Integration;

/// <summary>
/// AUD-R35-268. <c>ICodeGenerator</c> was public API that nothing in the library would ever call:
/// <c>Scaffolder.ScaffoldAsync</c> hard-coded <c>new EntityCodeGenerator(typeMapper)</c> and
/// <c>ScaffoldOptions</c> had no way to supply an alternative, so implementing the interface only
/// left a consumer calling it themselves. <c>ScaffoldOptions.CodeGenerator</c> is that injection
/// point; null still means the built-in generator.
/// </summary>
public class ScaffolderCodeGeneratorInjectionTests : IDisposable
{
    private readonly SqliteConnection _connection;
    private readonly string _connectionString;
    private readonly string _outputDir;

    public ScaffolderCodeGeneratorInjectionTests()
    {
        _connectionString = $"Data Source=CodeGenInjectionTest_{Guid.NewGuid():N};Mode=Memory;Cache=Shared";
        _connection = new SqliteConnection(_connectionString);
        _connection.Open();

        using SqliteCommand cmd = _connection.CreateCommand();
        cmd.CommandText = "CREATE TABLE products (product_id INTEGER PRIMARY KEY, product_name TEXT NOT NULL)";
        cmd.ExecuteNonQuery();

        _outputDir = Path.Combine(Path.GetTempPath(), $"JauntyCodeGenInjection_{Guid.NewGuid():N}");
    }

    public void Dispose()
    {
        _connection.Dispose();
        if (Directory.Exists(_outputDir))
            Directory.Delete(_outputDir, recursive: true);
        GC.SuppressFinalize(this);
    }

    private sealed class RecordingCodeGenerator : ICodeGenerator
    {
        public List<(string Table, CodeGeneratorOptions Options)> Calls { get; } = [];

        public string GenerateEntity(TableSchema table, CodeGeneratorOptions options)
        {
            Calls.Add((table.TableName, options));
            return $"// generated by {nameof(RecordingCodeGenerator)} for {table.TableName}";
        }
    }

    private ScaffoldOptions BaseOptions() =>
        new()
        {
            ConnectionString = _connectionString,
            Provider = DatabaseProvider.SQLite,
            OutputDirectory = _outputDir,
            Namespace = "Test.Entities"
        };

    [Fact]
    public async Task ASuppliedGenerator_RendersEveryTable_AndItsOutputIsWhatLandsOnDisk()
    {
        var generator = new RecordingCodeGenerator();
        ScaffoldOptions options = BaseOptions();
        options.CodeGenerator = generator;

        ScaffoldResult result = await new Scaffolder().ScaffoldAsync(options);

        Assert.True(result.Success);
        Assert.Equal(["products"], generator.Calls.Select(c => c.Table));

        var code = await File.ReadAllTextAsync(Path.Combine(_outputDir, "Product.cs"));
        Assert.Equal("// generated by RecordingCodeGenerator for products", code.Trim());
    }

    /// <summary>
    /// The supplied generator receives the same options the built-in one would, mapped from
    /// <c>ScaffoldOptions</c> - not a default-constructed set.
    /// </summary>
    [Fact]
    public async Task ASuppliedGenerator_ReceivesTheMappedCodeGeneratorOptions()
    {
        var generator = new RecordingCodeGenerator();
        ScaffoldOptions options = BaseOptions();
        options.CodeGenerator = generator;
        options.GenerateColumnAttribute = false;
        options.Singularize = false;

        ScaffoldResult result = await new Scaffolder().ScaffoldAsync(options);

        Assert.True(result.Success);
        (string _, CodeGeneratorOptions passed) = Assert.Single(generator.Calls);
        Assert.Equal("Test.Entities", passed.Namespace);
        Assert.False(passed.GenerateColumnAttribute);
        Assert.False(passed.Singularize);
    }

    [Fact]
    public async Task NoSuppliedGenerator_StillUsesTheBuiltInOne()
    {
        ScaffoldOptions options = BaseOptions();
        Assert.Null(options.CodeGenerator);

        ScaffoldResult result = await new Scaffolder().ScaffoldAsync(options);

        Assert.True(result.Success);
        var code = await File.ReadAllTextAsync(Path.Combine(_outputDir, "Product.cs"));
        Assert.Contains("public partial class Product", code, StringComparison.Ordinal);
    }
}
