<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <PackageReference Include="AutoMapper" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Microsoft.Data.Sqlite" />
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" />
    <PackageReference Include="Serilog" />
    <PackageReference Include="Serilog.Extensions.Logging" />
    <PackageReference Include="Serilog.Sinks.Console" />
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="MediatR" />
    <PackageReference Include="Swashbuckle.AspNetCore" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\..\src\Jaunty\Jaunty.csproj" />
    <ProjectReference Include="..\..\..\..\src\Jaunty.Fluent\Jaunty.Fluent.csproj" />
    <ProjectReference Include="..\..\..\..\src\Jaunty.Extensions.Reflection\Jaunty.Extensions.Reflection.csproj" />
  </ItemGroup>
</Project>
