#if NET8_0_OR_GREATER
using Jaunty.Dialects;

using Microsoft.Data.Sqlite;

using Xunit;

namespace Jaunty.Tests.Unit.Dialects;

/// <summary>
/// AUD-R26. The rest of this fix is verified against strings; this verifies it against SQLite.
///
/// <para>
/// The claim being tested is not "the generated SQL changed" but "the old SQL silently returned the
/// wrong answer". A dialect test asserting <c>SUBSTR(col, 2)</c> would pass just as happily if the
/// two-argument form did something else entirely - so the SQL each form generates is executed and
/// the results compared against the value that went in.
/// </para>
///
/// <para>
/// Microsoft.Data.Sqlite rather than System.Data.SQLite: the latter has no <c>osx-arm64</c>
/// <c>SQLite.Interop.dll</c>, which is the whole local test baseline gap, and this test needs to
/// actually run on a developer machine to be worth having.
/// </para>
/// </summary>
public class SubstringToEndTruncationTests
{
    /// <summary>Longer than the 8000 the old code hardcoded, so truncation is visible.</summary>
    private const int ValueLength = 10_000;

    private static SqliteConnection OpenWithLongValue()
    {
        var connection = new SqliteConnection("Data Source=:memory:");
        connection.Open();

        using SqliteCommand seed = connection.CreateCommand();
        seed.CommandText = $"CREATE TABLE t (s TEXT); INSERT INTO t VALUES (printf('%.*c', {ValueLength}, 'x'));";
        seed.ExecuteNonQuery();

        return connection;
    }

    private static string Scalar(SqliteConnection connection, string sql)
    {
        using SqliteCommand cmd = connection.CreateCommand();
        cmd.CommandText = sql;
        return (string)cmd.ExecuteScalar()!;
    }

    /// <summary>
    /// The defect, executed. This is what "silently truncates" means concretely: a predicate asking
    /// for everything from the second character on gets 8,000 of the 9,999 characters that are
    /// there, with no error and nothing to notice.
    /// </summary>
    [Fact]
    public void TheOldHardcoded8000_SilentlyTruncates()
    {
        using SqliteConnection connection = OpenWithLongValue();

        string old = Scalar(connection, "SELECT SUBSTR(s, 2, 8000) FROM t");

        Assert.Equal(8000, old.Length);
        Assert.NotEqual(ValueLength - 1, old.Length);
    }

    /// <summary>
    /// And the fix, executed: SQLite's own two-argument form, generated by the dialect rather than
    /// hand-written here, returns the whole remainder.
    /// </summary>
    [Fact]
    public void TheDialectsForm_ReturnsTheWholeRemainder()
    {
        using SqliteConnection connection = OpenWithLongValue();

        string generated = new SQLiteDialect().GenerateSubstringToEnd("s", "2");
        string result = Scalar(connection, $"SELECT {generated} FROM t");

        Assert.Equal(ValueLength - 1, result.Length);
    }

    /// <summary>
    /// The fallback for a dialect that does not implement the optional interface has to be
    /// non-truncating too - it is a sentinel, but one no real value can reach.
    /// </summary>
    [Fact]
    public void TheFallbackLength_DoesNotTruncateEither()
    {
        using SqliteConnection connection = OpenWithLongValue();

        string generated = new SQLiteDialect().GenerateSubstring("s", "2", SubstringToEnd.FallbackLength);
        string result = Scalar(connection, $"SELECT {generated} FROM t");

        Assert.Equal(ValueLength - 1, result.Length);
    }

    /// <summary>
    /// SQLite does not accept the ANSI <c>SUBSTRING(x FROM n)</c> form that PostgreSQL uses, which
    /// is why the two dialects generate different SQL rather than sharing one string. Measured, not
    /// assumed - it is the reason this is a per-dialect method at all.
    /// </summary>
    [Fact]
    public void Sqlite_RejectsTheAnsiFromForm()
    {
        using SqliteConnection connection = OpenWithLongValue();

        SqliteException ex = Assert.Throws<SqliteException>(
            () => Scalar(connection, "SELECT SUBSTRING(s FROM 2) FROM t"));

        Assert.Contains("syntax error", ex.Message, StringComparison.OrdinalIgnoreCase);
    }
}
#endif
