# build-artifacts.ps1
#
# Recurring, like merged-branch-sweep.ps1: it computes its targets at run time and becomes a
# no-op once run, so re-run it whenever the checkout gets fat. Written 2026-09-05, when the
# checkout measured 8,584 MB of which bin/ held 8,123 MB and obj/ 343 MB, most of it DuckDB's
# native library for every platform copied into every test and benchmark output, per framework,
# per configuration.
#
# Targets are directories named bin, obj, TestResults or BenchmarkDotNet.Artifacts anywhere
# below the repo root, plus .vs at the root. Every one of them is regenerated by dotnet build
# or dotnet test. Each target is checked with git at run time before it is touched: it must be
# ignored, and nothing inside it may be tracked. Junctions and symlinks are refused, never
# followed. tmp/, data/, seed/, audit/, work/ and docs/benchmark-artifacts/ are not targets and
# never will be: they hold things a build does not reproduce.
#
# Written, never run by the session. Run it yourself:
#
#   pwsh -NoProfile scripts/cleanup/build-artifacts.ps1                         # dry run, with sizes
#   pwsh -NoProfile scripts/cleanup/build-artifacts.ps1 -e                      # shut the build server, delete nothing
#   pwsh -NoProfile scripts/cleanup/build-artifacts.ps1 -e -DeleteBuildOutput   # delete
#
# -DeleteBuildOutput is the second flag because the targets are untracked files, even though a
# build gives them back. Stop Visual Studio or a running test host first; a locked file is
# reported and left, and the run exits non-zero.

[CmdletBinding()]
param(
    [Alias('e')][switch]$Execute,
    [switch]$DeleteBuildOutput
)

$ErrorActionPreference = 'Stop'
$PSNativeCommandUseErrorActionPreference = $false

$script:failed = $false

$Repo = 'C:\home\code\extrode.com\jaunty'
$TargetNames = @('bin', 'obj', 'TestResults', 'BenchmarkDotNet.Artifacts')
$NeverDescend = @('.git', 'tmp', 'data', 'seed', 'audit', 'work', 'node_modules', '.claude', '.worktrees')

function Step {
    param([string]$Description, [scriptblock]$Action)
    if ($Execute) {
        Write-Host "run:   $Description"
        & $Action
    }
    else {
        Write-Host "would: $Description"
    }
}

function Get-SizeMB {
    param([string]$Path)
    $bytes = (Get-ChildItem -LiteralPath $Path -Recurse -Force -File -ErrorAction SilentlyContinue |
        Measure-Object -Property Length -Sum).Sum
    return [math]::Round(($bytes / 1MB), 0)
}

function Find-Targets {
    param([string]$Dir)
    $found = @()
    foreach ($child in Get-ChildItem -LiteralPath $Dir -Directory -Force -ErrorAction SilentlyContinue) {
        if ($child.Attributes -band [IO.FileAttributes]::ReparsePoint) { continue }
        if ($NeverDescend -contains $child.Name) { continue }
        if ($TargetNames -contains $child.Name) {
            $found += $child.FullName
            continue
        }
        $found += Find-Targets -Dir $child.FullName
    }
    return $found
}

Write-Host ''
Write-Host '=== 0. Gate ==='
Write-Host ''

if (-not (Test-Path -LiteralPath (Join-Path $Repo '.git'))) {
    Write-Host "refuse: $Repo is not a git checkout."
    exit 1
}
Write-Host "ok:    $Repo"

Write-Host ''
Write-Host '=== 1. Build server ==='
Write-Host ''

Step 'dotnet build-server shutdown' {
    dotnet build-server shutdown > $null 2>&1
    if ($LASTEXITCODE -ne 0) { Write-Host '  build-server shutdown returned non-zero; continuing.' }
}

Write-Host ''
Write-Host '=== 2. Build output (needs -DeleteBuildOutput) ==='
Write-Host ''

$targets = @(Find-Targets -Dir $Repo)
$vs = Join-Path $Repo '.vs'
if (Test-Path -LiteralPath $vs) { $targets += $vs }

$totalMB = 0
$deletedMB = 0
foreach ($full in $targets | Sort-Object) {
    $rel = $full.Substring($Repo.Length + 1)

    $item = Get-Item -LiteralPath $full -Force
    if ($item.Attributes -band [IO.FileAttributes]::ReparsePoint) {
        Write-Host "refuse: $rel is a junction or symlink. Left alone."
        $script:failed = $true
        continue
    }

    git -C $Repo check-ignore -q -- $rel
    if ($LASTEXITCODE -ne 0) {
        Write-Host "refuse: $rel is not gitignored. Left alone."
        $script:failed = $true
        continue
    }

    $tracked = git -C $Repo ls-files -- $rel
    if ($tracked) {
        Write-Host "refuse: $rel contains tracked files. A cleanup script does not delete committed"
        Write-Host '        content; propose it as a commit instead. Left alone.'
        $script:failed = $true
        continue
    }

    $mb = Get-SizeMB $full
    $totalMB += $mb

    if (-not $DeleteBuildOutput) {
        Write-Host ("hold:  {0,6} MB  {1}  needs -DeleteBuildOutput as well as -e" -f $mb, $rel)
        continue
    }

    Step ("remove {0,6} MB  {1}" -f $mb, $rel) {
        try {
            Remove-Item -LiteralPath $full -Recurse -Force -ErrorAction Stop
            $script:deletedMB += $mb
        }
        catch {
            Write-Host "  locked or refused: $($_.Exception.Message.Trim()). Left alone."
            $script:failed = $true
        }
    }
}

Write-Host ''
Write-Host '=== 3. Remaining state ==='
Write-Host ''

Write-Host ("targets={0}  reclaimable={1} MB  deleted={2} MB" -f $targets.Count, $totalMB, $deletedMB)
$dirty = (git -C $Repo status --porcelain | Measure-Object).Count
Write-Host "uncommitted changes in tracked files: $dirty (a cleanup must not change this number)"

Write-Host ''
if (-not $Execute) {
    Write-Host 'Dry run. Nothing changed. Re-run with -e -DeleteBuildOutput to act.'
}

if ($Execute -and $script:failed) { exit 1 }
