using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Jaunty.SourceGenerator;

[Generator]
public class JauntyGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValuesProvider<ClassDeclarationSyntax> classDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, _) => IsSyntaxTargetForGeneration(s),
                transform: static (ctx, _) => GetSemanticTargetForGeneration(ctx))
            .Where(static m => m is not null)!;

        IncrementalValueProvider<(Compilation, ImmutableArray<ClassDeclarationSyntax>)> compilationAndClasses
            = context.CompilationProvider.Combine(classDeclarations.Collect());

        context.RegisterSourceOutput(compilationAndClasses,
            static (spc, source) => Execute(source.Item1, source.Item2, spc));
    }

    static bool IsSyntaxTargetForGeneration(SyntaxNode node)
        => node is ClassDeclarationSyntax { AttributeLists.Count: > 0 };

    static ClassDeclarationSyntax? GetSemanticTargetForGeneration(GeneratorSyntaxContext context)
    {
        var classDeclaration = (ClassDeclarationSyntax)context.Node;

        foreach (var attributeList in classDeclaration.AttributeLists)
        {
            foreach (var attribute in attributeList.Attributes)
            {
                var name = attribute.Name.ToString();
                if (name is "Table" or "Jaunty.Attributes.Table" or "TableAttribute" or "System.ComponentModel.DataAnnotations.Schema.TableAttribute")
                {
                    return classDeclaration;
                }
            }
        }

        return null;
    }

    static void Execute(Compilation compilation, ImmutableArray<ClassDeclarationSyntax> classes, SourceProductionContext context)
    {
        if (classes.IsDefaultOrEmpty)
            return;

        foreach (var classSyntax in classes.Distinct())
        {
            var model = compilation.GetSemanticModel(classSyntax.SyntaxTree);
            if (model.GetDeclaredSymbol(classSyntax) is not INamedTypeSymbol classSymbol)
                continue;

            var source = GenerateMapper(classSymbol);
            context.AddSource($"{classSymbol.Name}.JauntyMapper.g.cs", SourceText.From(source, Encoding.UTF8));
        }
    }

    static string GenerateMapper(INamedTypeSymbol classSymbol)
    {
        var namespaceName = classSymbol.ContainingNamespace.ToDisplayString();
        var className = classSymbol.Name;
        
        var allProperties = classSymbol.GetMembers().OfType<IPropertySymbol>()
            .Where(p => !p.IsStatic && p.DeclaredAccessibility == Accessibility.Public)
            .ToList();

        var properties = new List<PropertyMetadata>();
        foreach (var prop in allProperties)
        {
            // Support [Ignore] and [NotMapped]
            if (HasAttribute(prop, "IgnoreAttribute") || HasAttribute(prop, "NotMappedAttribute")) continue;

            // Support [Column] from both
            var columnAttr = GetAttribute(prop, "ColumnAttribute");
            var columnName = columnAttr?.ConstructorArguments.FirstOrDefault().Value?.ToString() ?? prop.Name;
            
            // Support [Key] from both, plus conventions
            var isKey = HasAttribute(prop, "KeyAttribute") || prop.Name.Equals("Id", StringComparison.OrdinalIgnoreCase) || prop.Name.Equals($"{className}Id", StringComparison.OrdinalIgnoreCase);
            
            // Support [DatabaseGenerated] from both
            var dbGenAttr = GetAttribute(prop, "DatabaseGeneratedAttribute");
            var isIdentity = false;
            if (dbGenAttr != null)
            {
                var arg = dbGenAttr.ConstructorArguments.FirstOrDefault();
                // Both Jaunty and DataAnnotations use 1 for Identity
                if (arg.Value is int val && val == 1) isIdentity = true;
            }
            else if (isKey && (prop.Type.SpecialType == SpecialType.System_Int32 || prop.Type.SpecialType == SpecialType.System_Int64))
            {
                isIdentity = true;
            }

            properties.Add(new PropertyMetadata(prop.Name, columnName, isKey, isIdentity, prop.Type.ToDisplayString()));
        }

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Data;");
        sb.AppendLine("using Jaunty.Interfaces;");
        sb.AppendLine();
        sb.AppendLine($"namespace {namespaceName}");
        sb.AppendLine("{");
        sb.AppendLine($"    public partial class {className} : IMapped<{className}>");
        sb.AppendLine("    {");
        sb.AppendLine("        public readonly struct ColumnInfo");
        sb.AppendLine("        {");
        sb.AppendLine("            public ColumnInfo(string columnName, string propertyName, bool isPrimaryKey, bool isIdentity)");
        sb.AppendLine("            {");
        sb.AppendLine("                ColumnName = columnName;");
        sb.AppendLine("                PropertyName = propertyName;");
        sb.AppendLine("                IsPrimaryKey = isPrimaryKey;");
        sb.AppendLine("                IsIdentity = isIdentity;");
        sb.AppendLine("            }");
        sb.AppendLine("            public string ColumnName { get; }");
        sb.AppendLine("            public string PropertyName { get; }");
        sb.AppendLine("            public bool IsPrimaryKey { get; }");
        sb.AppendLine("            public bool IsIdentity { get; }");
        sb.AppendLine("        }");
        sb.AppendLine();

        // 1. ReadEntity
        sb.AppendLine("        #if NET8_0_OR_GREATER");
        sb.AppendLine($"        public static {className} ReadEntity(IDataReader reader)");
        sb.AppendLine("        #else");
        sb.AppendLine($"        public {className} ReadEntity(IDataReader reader)");
        sb.AppendLine("        #endif");
        sb.AppendLine("        {");
        sb.AppendLine("            var ord = OrdinalMap.Resolve(reader);");
        sb.AppendLine($"            var entity = new {className}();");
        for (int i = 0; i < properties.Count; i++)
        {
            var p = properties[i];
            var getter = GetReaderMethod(p.TypeName);
            sb.AppendLine($"            if (!reader.IsDBNull(ord[{i}]))");
            sb.AppendLine("            {");
            if (getter != null)
            {
                sb.AppendLine($"                entity.{p.PropertyName} = {getter}(ord[{i}]);");
            }
            else
            {
                sb.AppendLine($"                entity.{p.PropertyName} = ({p.TypeName})reader.GetValue(ord[{i}]);");
            }
            sb.AppendLine("            }");
        }
        sb.AppendLine("            return entity;");
        sb.AppendLine("        }");

        // 2. BindInsert
        sb.AppendLine($"        public static void BindInsert(IDbCommand command, {className} entity)");
        sb.AppendLine("        {");
        sb.AppendLine("            var p = command.Parameters;");
        foreach (var p in properties.Where(x => !x.IsIdentity))
        {
            sb.AppendLine($"            AddParam(command, p, \"@{p.ColumnName}\", entity.{p.PropertyName});");
        }
        sb.AppendLine("        }");

        // 3. BindUpdate
        sb.AppendLine($"        public static void BindUpdate(IDbCommand command, {className} entity)");
        sb.AppendLine("        {");
        sb.AppendLine("            var p = command.Parameters;");
        foreach (var p in properties.Where(x => !x.IsPrimaryKey && !x.IsIdentity))
        {
            sb.AppendLine($"            AddParam(command, p, \"@{p.ColumnName}\", entity.{p.PropertyName});");
        }
        foreach (var p in properties.Where(x => x.IsPrimaryKey))
        {
            sb.AppendLine($"            AddParam(command, p, \"@{p.ColumnName}\", entity.{p.PropertyName});");
        }
        sb.AppendLine("        }");

        // 4. BindDelete
        sb.AppendLine($"        public static void BindDelete(IDbCommand command, {className} entity)");
        sb.AppendLine("        {");
        sb.AppendLine("            var p = command.Parameters;");
        foreach (var p in properties.Where(x => x.IsPrimaryKey))
        {
            sb.AppendLine($"            AddParam(command, p, \"@{p.ColumnName}\", entity.{p.PropertyName});");
        }
        sb.AppendLine("        }");

        sb.AppendLine("        private static void AddParam(IDbCommand cmd, IDataParameterCollection pc, string name, object? value)");
        sb.AppendLine("        {");
        sb.AppendLine("            var p = cmd.CreateParameter();");
        sb.AppendLine("            p.ParameterName = name;");
        sb.AppendLine("            p.Value = value ?? DBNull.Value;");
        sb.AppendLine("            pc.Add(p);");
        sb.AppendLine("        }");

        sb.AppendLine("        private static class OrdinalMap");
        sb.AppendLine("        {");
        sb.AppendLine("            private static int[]? _ordinals;");
        sb.AppendLine("            private static int _fieldCount;");
        sb.AppendLine();
        sb.AppendLine($"            public static int[] Resolve(IDataReader reader)");
        sb.AppendLine("            {");
        sb.AppendLine("                var fc = reader.FieldCount;");
        sb.AppendLine("                var cached = _ordinals;");
        sb.AppendLine("                if (cached is not null && _fieldCount == fc)");
        sb.AppendLine("                    return cached;");
        sb.AppendLine();
        sb.AppendLine($"                var ords = new int[{properties.Count}];");
        for (int i = 0; i < properties.Count; i++)
        {
            sb.AppendLine($"                ords[{i}] = reader.GetOrdinal(\"{properties[i].ColumnName}\");");
        }
        sb.AppendLine("                _fieldCount = fc;");
        sb.AppendLine("                _ordinals = ords;");
        sb.AppendLine("                return ords;");
        sb.AppendLine("            }");
        sb.AppendLine("        }");

        var insertProps = properties.Where(x => !x.IsIdentity).ToList();
        var updateProps = properties.Where(x => !x.IsPrimaryKey && !x.IsIdentity).ToList();
        var deleteProps = properties.Where(x => x.IsPrimaryKey).ToList();

        sb.AppendLine();
        sb.AppendLine("        public static System.Collections.Generic.IReadOnlyList<ColumnInfo> InsertColumns { get; }");
        sb.AppendLine("            = new ColumnInfo[] {");
        for (int i = 0; i < insertProps.Count; i++)
        {
            var p = insertProps[i];
            sb.AppendLine($"            new ColumnInfo(\"{p.ColumnName}\", \"{p.PropertyName}\", {p.IsPrimaryKey.ToString().ToLower()}, {p.IsIdentity.ToString().ToLower()}),");
        }
        sb.AppendLine("        };");

        sb.AppendLine();
        sb.AppendLine("        public static System.Collections.Generic.IReadOnlyList<ColumnInfo> UpdateColumns { get; }");
        sb.AppendLine("            = new ColumnInfo[] {");
        for (int i = 0; i < updateProps.Count; i++)
        {
            var p = updateProps[i];
            sb.AppendLine($"            new ColumnInfo(\"{p.ColumnName}\", \"{p.PropertyName}\", {p.IsPrimaryKey.ToString().ToLower()}, {p.IsIdentity.ToString().ToLower()}),");
        }
        sb.AppendLine("        };");

        sb.AppendLine();
        sb.AppendLine("        public static System.Collections.Generic.IReadOnlyList<ColumnInfo> DeleteColumns { get; }");
        sb.AppendLine("            = new ColumnInfo[] {");
        for (int i = 0; i < deleteProps.Count; i++)
        {
            var p = deleteProps[i];
            sb.AppendLine($"            new ColumnInfo(\"{p.ColumnName}\", \"{p.PropertyName}\", {p.IsPrimaryKey.ToString().ToLower()}, {p.IsIdentity.ToString().ToLower()}),");
        }
        sb.AppendLine("        };");

        sb.AppendLine();
        sb.AppendLine("        public static System.Collections.Generic.Dictionary<string, ColumnInfo> ParameterMap { get; }");
        sb.AppendLine("            = new System.Collections.Generic.Dictionary<string, ColumnInfo>(System.StringComparer.OrdinalIgnoreCase)");
        sb.AppendLine("            {");
        for (int i = 0; i < properties.Count; i++)
        {
            var p = properties[i];
            sb.AppendLine($"            [\"{p.ColumnName}\"] = new ColumnInfo(\"{p.ColumnName}\", \"{p.PropertyName}\", {p.IsPrimaryKey.ToString().ToLower()}, {p.IsIdentity.ToString().ToLower()}),");
        }
        sb.AppendLine("        };");

        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static bool HasAttribute(ISymbol symbol, string attributeName) 
        => symbol.GetAttributes().Any(a => a.AttributeClass?.Name == attributeName);

    private static AttributeData? GetAttribute(ISymbol symbol, string attributeName)
        => symbol.GetAttributes().FirstOrDefault(a => a.AttributeClass?.Name == attributeName);

    private static string? GetReaderMethod(string typeName)
    {
        return typeName switch
        {
            "int" or "Int32" or "int?" or "Int32?" or "System.Int32" => "reader.GetInt32",
            "long" or "Int64" or "long?" or "Int64?" or "System.Int64" => "reader.GetInt64",
            "string" or "String" or "string?" or "String?" or "System.String" => "reader.GetString",
            "bool" or "Boolean" or "bool?" or "Boolean?" or "System.Boolean" => "reader.GetBoolean",
            "decimal" or "Decimal" or "decimal?" or "Decimal?" or "System.Decimal" => "reader.GetDecimal",
            "double" or "Double" or "double?" or "Double?" or "System.Double" => "reader.GetDouble",
            "float" or "Single" or "float?" or "Single?" or "System.Single" => "reader.GetFloat",
            "short" or "Int16" or "short?" or "Int16?" or "System.Int16" => "reader.GetInt16",
            "byte" or "Byte" or "byte?" or "Byte?" or "System.Byte" => "reader.GetByte",
            "Guid" or "Guid?" or "System.Guid" => "reader.GetGuid",
            "DateTime" or "DateTime?" or "System.DateTime" => "reader.GetDateTime",
            _ => null
        };
    }

    private struct PropertyMetadata(string propertyName, string columnName, bool isPrimaryKey, bool isIdentity, string typeName)
    {
        public string PropertyName = propertyName;
        public string ColumnName = columnName;
        public bool IsPrimaryKey = isPrimaryKey;
        public bool IsIdentity = isIdentity;
        public string TypeName = typeName;
    }
}
