using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Jaunty.SourceGenerator;

[Generator]
public class JauntyGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Filter for classes that might need a mapper
        IncrementalValuesProvider<ClassDeclarationSyntax> classDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, _) => IsSyntaxTargetForGeneration(s),
                transform: static (ctx, _) => GetSemanticTargetForGeneration(ctx))
            .Where(static m => m is not null)!;

        // Combine with compilation
        IncrementalValueProvider<(Compilation, ImmutableArray<ClassDeclarationSyntax>)> compilationAndClasses
            = context.CompilationProvider.Combine(classDeclarations.Collect());

        // Register the source output
        context.RegisterSourceOutput(compilationAndClasses,
            static (spc, source) => Execute(source.Item1, source.Item2, spc));
    }

    static bool IsSyntaxTargetForGeneration(SyntaxNode node)
        => node is ClassDeclarationSyntax { AttributeLists.Count: > 0 };

    static ClassDeclarationSyntax? GetSemanticTargetForGeneration(GeneratorSyntaxContext context)
    {
        var classDeclaration = (ClassDeclarationSyntax)context.Node;

        foreach (var attributeList in classDeclaration.AttributeLists)
        {
            foreach (var attribute in attributeList.Attributes)
            {
                var name = attribute.Name.ToString();
                if (name is "Table" or "Jaunty.Attributes.Table" or "TableAttribute")
                {
                    return classDeclaration;
                }
            }
        }

        return null;
    }

    static void Execute(Compilation compilation, ImmutableArray<ClassDeclarationSyntax> classes, SourceProductionContext context)
    {
        if (classes.IsDefaultOrEmpty)
            return;

        foreach (var classSyntax in classes.Distinct())
        {
            var model = compilation.GetSemanticModel(classSyntax.SyntaxTree);
            if (model.GetDeclaredSymbol(classSyntax) is not INamedTypeSymbol classSymbol)
                continue;

            var source = GenerateMapper(classSymbol);
            context.AddSource($"{classSymbol.Name}.JauntyMapper.g.cs", SourceText.From(source, Encoding.UTF8));
        }
    }

    static string GenerateMapper(INamedTypeSymbol classSymbol)
    {
        var namespaceName = classSymbol.ContainingNamespace.ToDisplayString();
        var className = classSymbol.Name;
        
        var allProperties = classSymbol.GetMembers().OfType<IPropertySymbol>()
            .Where(p => !p.IsStatic && p.DeclaredAccessibility == Accessibility.Public)
            .ToList();

        var properties = new List<PropertyMetadata>();
        foreach (var prop in allProperties)
        {
            if (HasAttribute(prop, "IgnoreAttribute")) continue;

            var columnAttr = GetAttribute(prop, "ColumnAttribute");
            var columnName = columnAttr?.ConstructorArguments.FirstOrDefault().Value?.ToString() ?? prop.Name;
            var isKey = HasAttribute(prop, "KeyAttribute") || prop.Name.Equals("Id", StringComparison.OrdinalIgnoreCase) || prop.Name.Equals($"{className}Id", StringComparison.OrdinalIgnoreCase);
            
            var dbGenAttr = GetAttribute(prop, "DatabaseGeneratedAttribute");
            var isIdentity = false;
            if (dbGenAttr != null)
            {
                var arg = dbGenAttr.ConstructorArguments.FirstOrDefault();
                if (arg.Value is int val && val == 1) isIdentity = true;
            }
            else if (isKey && (prop.Type.SpecialType == SpecialType.System_Int32 || prop.Type.SpecialType == SpecialType.System_Int64))
            {
                isIdentity = true;
            }

            properties.Add(new PropertyMetadata(prop.Name, columnName, isKey, isIdentity, prop.Type.ToDisplayString(), IsNullable(prop.Type)));
        }

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Data;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using Jaunty.Interfaces;");
        sb.AppendLine();
        sb.AppendLine($"namespace {namespaceName}");
        sb.AppendLine("{");
        sb.AppendLine($"    public partial class {className} : IMapped<{className}>");
        sb.AppendLine("    {");

        // 1. ReadEntity
        sb.AppendLine("        #if NET8_0_OR_GREATER");
        sb.AppendLine($"        public static {className} ReadEntity(IDataReader reader)");
        sb.AppendLine("        #else");
        sb.AppendLine($"        public {className} ReadEntity(IDataReader reader)");
        sb.AppendLine("        #endif");
        sb.AppendLine("        {");
        sb.AppendLine("            var ord = new OrdinalCache(reader);");
        sb.AppendLine($"            var entity = new {className}();");
        foreach (var p in properties)
        {
            sb.AppendLine($"            if (!reader.IsDBNull(ord[\"{p.ColumnName}\"]))");
            sb.AppendLine("            {");
            var getter = GetReaderMethod(p.TypeName);
            sb.AppendLine($"                entity.{p.PropertyName} = {getter}(ord[\"{p.ColumnName}\"]);");
            sb.AppendLine("            }");
        }
        sb.AppendLine("            return entity;");
        sb.AppendLine("        }");

        // 2. BindInsert
        sb.AppendLine($"        public static void BindInsert(IDbCommand command, {className} entity)");
        sb.AppendLine("        {");
        sb.AppendLine("            var p = command.Parameters;");
        foreach (var p in properties.Where(x => !x.IsIdentity))
        {
            sb.AppendLine($"            AddParam(command, p, \"@{p.PropertyName}\", entity.{p.PropertyName});");
        }
        sb.AppendLine("        }");

        // 3. BindUpdate
        sb.AppendLine($"        public static void BindUpdate(IDbCommand command, {className} entity)");
        sb.AppendLine("        {");
        sb.AppendLine("            var p = command.Parameters;");
        // SET
        foreach (var p in properties.Where(x => !x.IsPrimaryKey && !x.IsIdentity))
        {
            sb.AppendLine($"            AddParam(command, p, \"@{p.PropertyName}\", entity.{p.PropertyName});");
        }
        // WHERE
        foreach (var p in properties.Where(x => x.IsPrimaryKey))
        {
            sb.AppendLine($"            AddParam(command, p, \"@{p.PropertyName}\", entity.{p.PropertyName});");
        }
        sb.AppendLine("        }");

        // 4. BindDelete
        sb.AppendLine($"        public static void BindDelete(IDbCommand command, {className} entity)");
        sb.AppendLine("        {");
        sb.AppendLine("            var p = command.Parameters;");
        foreach (var p in properties.Where(x => x.IsPrimaryKey))
        {
            sb.AppendLine($"            AddParam(command, p, \"@{p.PropertyName}\", entity.{p.PropertyName});");
        }
        sb.AppendLine("        }");

        // Helper: AddParam
        sb.AppendLine("        private static void AddParam(IDbCommand cmd, IDataParameterCollection pc, string name, object? value)");
        sb.AppendLine("        {");
        sb.AppendLine("            var p = cmd.CreateParameter();");
        sb.AppendLine("            p.ParameterName = name;");
        sb.AppendLine("            p.Value = value ?? DBNull.Value;");
        sb.AppendLine("            pc.Add(p);");
        sb.AppendLine("        }");

        // Helper: OrdinalCache (Inlined per class for AOT safety)
        sb.AppendLine("        private readonly struct OrdinalCache(IDataReader reader)");
        sb.AppendLine("        {");
        sb.AppendLine("            private readonly IDataReader _reader = reader;");
        sb.AppendLine("            private readonly Dictionary<string, int> _cache = new Dictionary<string, int>(StringComparer.OrdinalIgnoreCase);");
        sb.AppendLine("            public int this[string columnName] => _cache.TryGetValue(columnName, out var ord) ? ord : _cache[columnName] = _reader.GetOrdinal(columnName);");
        sb.AppendLine("        }");

        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static bool HasAttribute(ISymbol symbol, string attributeName) 
        => symbol.GetAttributes().Any(a => a.AttributeClass?.Name == attributeName);

    private static AttributeData? GetAttribute(ISymbol symbol, string attributeName)
        => symbol.GetAttributes().FirstOrDefault(a => a.AttributeClass?.Name == attributeName);

    private static bool IsNullable(ITypeSymbol type) => type.NullableAnnotation == NullableAnnotation.Annotated || type.IsReferenceType || type.OriginalDefinition.SpecialType == SpecialType.System_Nullable_T;

    private static string GetReaderMethod(string typeName)
    {
        return typeName switch
        {
            "int" or "Int32" or "int?" => "reader.GetInt32",
            "long" or "Int64" or "long?" => "reader.GetInt64",
            "string" or "String" => "reader.GetString",
            "bool" or "Boolean" or "bool?" => "reader.GetBoolean",
            "decimal" or "Decimal" or "decimal?" => "reader.GetDecimal",
            "double" or "Double" or "double?" => "reader.GetDouble",
            "float" or "Single" or "float?" => "reader.GetFloat",
            "short" or "Int16" or "short?" => "reader.GetInt16",
            "byte" or "Byte" or "byte?" => "reader.GetByte",
            "Guid" or "Guid?" => "reader.GetGuid",
            "DateTime" or "DateTime?" => "reader.GetDateTime",
            _ => "((" + typeName + ")reader.GetValue)" // Fallback
        };
    }

    private struct PropertyMetadata(string propertyName, string columnName, bool isPrimaryKey, bool isIdentity, string typeName, bool isNullable)
    {
        public string PropertyName = propertyName;
        public string ColumnName = columnName;
        public bool IsPrimaryKey = isPrimaryKey;
        public bool IsIdentity = isIdentity;
        public string TypeName = typeName;
        public bool IsNullable = isNullable;
    }
}
