#!/usr/bin/env python3
"""Generate data/sqlserver/create-northwind.sql from data/sqlite/Northwind.db.

The Jaunty test suite targets the classic PascalCase Northwind schema on SQL
Server (Categories.CategoryId, Products.ProductId, ...). Snake_case access
(stored procedures, entity [Column] attributes) is bridged at test time by
DialectFixture, which adds computed snake_case columns to the PascalCase
tables on a case-insensitive database.

Regenerate whenever the SQLite reference database changes:

    python scripts/generate-sqlserver-northwind.py
"""
import re
import sqlite3
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "data" / "sqlite" / "Northwind.db"
DST = ROOT / "data" / "sqlserver" / "create-northwind.sql"

TYPE_MAP = [
    (re.compile(r"\bINTEGER\b", re.I), "int"),
    (re.compile(r"\bREAL\b", re.I), "float"),
    (re.compile(r"\bTEXT\b", re.I), "nvarchar(max)"),
    (re.compile(r"\bBLOB\b", re.I), "varbinary(max)"),
    (re.compile(r"\bVARCHAR\(", re.I), "nvarchar("),
    (re.compile(r"\bCHAR\(", re.I), "nchar("),
    (re.compile(r"\bSMALLINT\b", re.I), "smallint"),
    (re.compile(r"\bDATE\b", re.I), "datetime"),
    (re.compile(r"\bBOOLEAN\b", re.I), "bit"),
    (re.compile(r"\bFALSE\b"), "0"),
    (re.compile(r"\bTRUE\b"), "1"),
]

# Entity contracts override declared SQLite types where providers differ:
# Product.CategoryId is short?, so the SQL Server column must be smallint
# (SQLite's dynamic typing hid the mismatch). The products->categories FK is
# dropped because smallint cannot reference the int Categories.CategoryId.
COLUMN_TYPE_OVERRIDES = {
    ("products", "category_id"): "smallint",
}
DROP_FKS = {"fk_products__categories"}

# Insert order must satisfy FK dependencies.
TABLE_ORDER = [
    "region", "territories", "customer_demographics", "customers",
    "customer_customer_demo", "employees", "employee_territories",
    "categories", "suppliers", "products", "shippers", "orders",
    "order_details",
]


def pascal(name: str) -> str:
    if "_" not in name and not name.islower():
        return name  # already PascalCase (e.g. re-processed FK column)
    return "".join(part.capitalize() for part in name.split("_"))


def translate_schema(sql: str, table: str, col_names: list[str]) -> str:
    for rx, repl in TYPE_MAP:
        sql = rx.sub(repl, sql)
    # Pascal-case the table name and every column identifier.
    sql = re.sub(rf"\bCREATE TABLE {table}\b", f"CREATE TABLE {pascal(table)}", sql)
    for c in sorted(col_names, key=len, reverse=True):
        sql = re.sub(rf"\b{c}\b", pascal(c), sql)
    # FK targets: REFERENCES other_table (other_col) — pascal both identifiers
    # (the referenced column belongs to another table, so the per-table column
    # pass above does not rewrite it).
    sql = re.sub(
        r"\bREFERENCES (\w+)\s*\(\s*(\w+)\s*\)",
        lambda m: f"REFERENCES {pascal(m.group(1))} ({pascal(m.group(2))})",
        sql,
    )
    # SQLite scopes constraint names per table; SQL Server requires database
    # uniqueness, and the SQLite schema reuses names like ck_unit_price.
    sql = re.sub(r"CONSTRAINT (ck_)", f"CONSTRAINT \\g<1>{table}_", sql)
    for (t, col), sqltype in COLUMN_TYPE_OVERRIDES.items():
        if t == table:
            sql = re.sub(
                rf"^(\s*{pascal(col)}\s+)\w+", rf"\g<1>{sqltype}", sql, flags=re.M
            )
    for fk in DROP_FKS:
        sql = re.sub(
            rf",?\s*CONSTRAINT {fk} FOREIGN KEY\s*\([^)]*\)\s*REFERENCES\s+\w+\s*\([^)]*\)",
            "",
            sql,
        )
    return sql


def sql_literal(value) -> str:
    if value is None:
        return "NULL"
    if isinstance(value, bytes):
        return "0x" + value.hex() if value else "0x00"
    if isinstance(value, (int, float)):
        return repr(value)
    s = str(value).replace("'", "''")
    return f"N'{s}'"


def main() -> None:
    con = sqlite3.connect(str(SRC))
    con.text_factory = lambda b: b.decode("utf-8", "replace")
    tables = {
        name: sql
        for name, sql in con.execute(
            "SELECT name, sql FROM sqlite_master WHERE type='table'"
        )
    }
    missing = [t for t in TABLE_ORDER if t not in tables]
    if missing:
        raise SystemExit(f"tables missing from SQLite db: {missing}")

    out = [
        "-- AUTO-GENERATED by scripts/generate-sqlserver-northwind.py — do not edit.",
        "-- Bootstraps the Northwind test database for SQL Server integration tests.",
        "-- PascalCase tables + snake_case updatable views on a case-sensitive",
        "-- collation; see the generator script header for why.",
        "-- Usage: sqlcmd -S <server> -U sa -P <password> -i create-northwind.sql",
        "",
        "IF DB_ID('Northwind') IS NULL CREATE DATABASE Northwind;",
        "GO",
        "USE Northwind;",
        "GO",
        "",
    ]

    for t in reversed(TABLE_ORDER):
        out.append(
            f"IF OBJECT_ID('dbo.{pascal(t)}', 'U') IS NOT NULL DROP TABLE dbo.{pascal(t)};"
        )
    out.append("GO")
    out.append("")

    col_cache: dict[str, list[str]] = {}
    for t in TABLE_ORDER:
        cols = [r[1] for r in con.execute(f'PRAGMA table_info("{t}")')]
        col_cache[t] = cols
        out.append(translate_schema(tables[t], t, cols) + ";")
        out.append("GO")
        # Computed snake_case bridge columns (same convention DialectFixture
        # applies at test time) so stored procedures referencing snake_case
        # names compile against this schema.
        for c in cols:
            # Single-word names (address/Address) already resolve on the
            # case-insensitive database; only underscore names need bridging.
            if "_" in c:
                out.append(
                    f"ALTER TABLE dbo.{pascal(t)} ADD {c} AS ({pascal(c)});"
                )
        out.append("GO")
        out.append("")

    for t in TABLE_ORDER:
        rows = con.execute(f'SELECT * FROM "{t}"').fetchall()
        if not rows:
            continue
        col_list = ", ".join(pascal(c) for c in col_cache[t])
        for i in range(0, len(rows), 100):
            chunk = rows[i : i + 100]
            values = ",\n".join(
                "(" + ", ".join(sql_literal(v) for v in row) + ")" for row in chunk
            )
            out.append(f"INSERT INTO dbo.{pascal(t)} ({col_list}) VALUES\n{values};")
        out.append("GO")
        out.append("")

    DST.write_text("\n".join(out), encoding="utf-8", newline="\n")
    print(f"wrote {DST} ({DST.stat().st_size // 1024} KB)")


if __name__ == "__main__":
    main()
